### ISSUE TITLE
Potential issue with generated C code for iso2

### ISSUE THREAD

**Issue by PKrza** [EVerest/cbexigen#14]
Quick background:
I was using the decoder functions from your previous project (openV2G, at least I assume it was yours since the syntax is pretty much the same) and wanted to switch to this project since I need the -20 support.

I was looking at the generated code functions for -2, specifically the decode_iso2_SignedInfoType() function, and I noticed that you are not decoding Reference field as an array, which differs from openV2G project. Here is the comparison:
openV2G:
```
#define iso2SignedInfoType_Reference_ARRAY_SIZE 1
struct iso2SignedInfoType {
	struct {
		exi_string_character_t characters[iso2SignedInfoType_Id_CHARACTERS_SIZE];
		uint16_t charactersLen;
	}  Id ;
	unsigned int Id_isUsed;
	struct iso2CanonicalizationMethodType CanonicalizationMethod ;
	struct iso2SignatureMethodType SignatureMethod ;
	struct {
		struct iso2ReferenceType array[iso2SignedInfoType_Reference_ARRAY_SIZE];
		uint16_t arrayLen;
	} Reference;
};
```
cbexigen:
```
struct iso2_SignedInfoType {
    struct {
        char characters[iso2_Id_CHARACTER_SIZE];
        uint16_t charactersLen;
    } Id;
    unsigned int Id_isUsed:1;
    struct iso2_CanonicalizationMethodType CanonicalizationMethod;
    struct iso2_SignatureMethodType SignatureMethod;
    struct iso2_ReferenceType Reference;
};
```
And lastly, the Reference entrance from the XML schemas:
```
<element name="SignedInfo" type="ds:SignedInfoType"/>
    <complexType name="SignedInfoType">
        <sequence>
            <element ref="ds:CanonicalizationMethod"/>
            <element ref="ds:SignatureMethod"/>
            <element ref="ds:Reference" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="Id" type="ID" use="optional"/>
    </complexType>
```

The Reference field has maxOccurs="unbounded" which should mean that it should be an array.

Just checking if this is an issue or did I understood it wrong.

**Comment by barsnick** [comment]
This project is not associated with OpenV2G, though it seemed logical to create a similar interface/API to OpenV2G initially, for easier transition. This project cbExiGen/cbV2G aims to provide an open source ISO 15118-20 codec, which OpenV2G does not plan to provide (you need to pay for an implementation). At the same time, DIN 70121 and ISO 15118-2 shall of course also be supported.

Regarding your observation:
Indeed, we artificially reduced the size of Reference to 1:
https://github.com/EVerest/cbexigen/blob/3e78459a68cab0ab272a65ee78b0ee9daaf909fe/src/cbexigen/typeDefinitions.py#L41

But since OpenV2G provides an array, we probably also should provide this. The logic for identifying arrays reduced to one and retaining them as array is not yet in place, but work in progress. Thanks for pointing out this particular restriction.

Note: OpenV2G does also only provide room for decoding one single Reference:
https://github.com/chargebyte/openv2g/blob/87591ab3b7172d9661c118a318c60a0ce2be240e/src/xmldsig/xmldsigEXIDatatypes.h#L448
```#define xmldsigManifestType_Reference_ARRAY_SIZE 1```

So, in the meantime, as either library only accepts one Reference, you can replace the array access with access to the single provided variable.

**Comment by PKrza** [comment]
It is true that the default array size for Reference is set to 1 by default, but in my adaptation, I've increased the value to 10.
This is probably done to accommodate the encoded message, but since it was long time ago, I cannot recall how the encoded message looked like.

I can try and dig up the encoded bytes and send it to you so you have some testcase. That is, if there are indeed multiple References.

**Comment by barsnick** [comment]
Good point. We strive to have an API which does not change significantly with the modification of such restrictions.

Do I understand correctly that OpenV2G also cannot decode this message unless you lift its quoted limitation?

Please do provide the testcase. If you even have both EXI and XML (or some other representation such as JSON), that would be great.

**Comment by barsnick** [comment]
Thanks for the explanation of your motivation. This is one of the goals we also see.
Thanks also for the inputs.

> This is probably done to accommodate the encoded message

I thought you had an actual message with more than one Reference. We can create it ourselves using Josev/iso15118 though.

Feel free to share your integrations of OpenV2G and cbV2G for the community. ;-)

**Comment by PKrza** [comment]
Yeah, I thought so too, but it was just one reference.

I definitely plan to release something when I finish it :)

**Comment by barsnick** [comment]
For the sake of debugging, I am attaching your inputs, complemented with pretty-printed JSON, and with EXI streams as hex-encoded strings.
[AuthReqEncode.txt](https://github.com/EVerest/cbexigen/files/12302830/AuthReqEncode.txt)
[CertInstallationReqEncode.txt](https://github.com/EVerest/cbexigen/files/12302832/CertInstallationReqEncode.txt)

**Comment by barsnick** [comment]
Hello @PKrza,
could you kindly test the codec, as generated from current branch [main](https://github.com/EVerest/cbexigen/tree/main) (commit https://github.com/EVerest/cbexigen/commit/82976af6a0ff7a4946bfd19e349bbc4f2b53fabf)?

We increased the array size of References to 4, as mandated by ISO 15118-2 [V2G2-909]. We kept the size for DIN at 1, since it is unused.

We also fixed a lot of coding errors.

Thanks for your input, and looking forward to your integrations.

**Comment by barsnick** [comment]
Closing, as `Reference`s now appear as an array (in ISO 15118-2), albeit with a preconfigured limit of 4 (instead of `unlimited`), as stated by requirement [V2G2-909]:
> The signature shall not reference more than 4 signed elements.
