### ISSUE TITLE
ISO-20 Missing SupportedProvidersListType array 

### ISSUE THREAD

**Issue by SebaLukas** [EVerest/cbexigen#18]
Hi :)

In the `AuthorizationSetupRes`, the following applies to the `SupportedProviders` element in the `PnC_ASResAuthorizationMode` element:

```
<xs:complexType name="SupportedProvidersListType">
	<xs:sequence>
		<xs:element name="ProviderID" type="v2gci_ct:nameType" maxOccurs="128"/>
	</xs:sequence>
</xs:complexType>
```

In the generated code, the `ProviderID` is just a string (char array) but not a list or array of strings:
```
struct iso20_SupportedProvidersListType {
    // ProviderID, nameType (base: string)
    struct {
        char characters[iso20_ProviderID_CHARACTER_SIZE];
        uint16_t charactersLen;
    } ProviderID;

};
```
Can you guys please take a look at this?

Many greetings
Sebastian

**Comment by chausGit** [comment]
Correct, however we have ignored the problem so far, as it has not yet had any impact for us.

But with the -20, the problem seems to be acute.

This actually affects all arrays of simple types, but which are coded as array and length byte in a struct, so quasi array of array struct. https://github.com/EVerest/cbexigen/issues/19 seems to have the same cause
