### ISSUE TITLE
ISO20 SubCertificates missing list of certificates

### ISSUE THREAD

**Issue by SebaLukas** [EVerest/cbexigen#19]
Hi :)

in the `AuthorizationReq` message the following is true for the `SubCertificates` element in the `ContractCertificateChainType` element:
```
<xs:complexType name="SubCertificatesType">
	<xs:sequence>
		<xs:element name="Certificate" type="certificateType" maxOccurs="3"/>
	</xs:sequence>
</xs:complexType>
```
In the generated code, the `SubCertificates` is defined only as a single certificate but not as a list of certificates:
```
struct iso20_SubCertificatesType {
    // Certificate, certificateType (base: base64Binary)
    struct {
        uint8_t bytes[iso20_certificateType_BYTES_SIZE];
        uint16_t bytesLen;
    } Certificate;


};
```
Can you guys please take a look at this? :D

Many greetings
Sebastian

**Comment by chausGit** [comment]
Correct, however we have ignored the problem so far, as it has not yet had any impact for us.

But with the -20, the problem seems to be acute.

This actually affects all arrays of simple types, but which are coded as array and length byte in a struct, so quasi array of array struct. https://github.com/EVerest/cbexigen/issues/18 seems to have the same cause
