### ISSUE TITLE
Update xmlschema to the latest version to support Python 3.12

### ISSUE THREAD

**Issue by SebaLukas** [EVerest/cbexigen#59]
Hello everyone,

there seems to be a problem with the Python package xmlschema version 1.11.3 and Python 3.12.
When importing xmlschema in Python 3.12 there is an error. And of course generating EXI code does not work either.
Python 3.11 and below works without problems.

Are there any reasons not to use the latest version 2.5.0 for xmlschema for cbexigen?
Python >= 3.7 should still be supported with this version.

I was able to generate exi code yesterday with xmlschema (2.5.0) without any problems.

Best regards
Sebastian

**Comment by SebaLukas** [comment]
Testing is not a problem for me. Especially with ISO-20 I can easily test the generated EXI code, as I am currently only working on libiso15118.

Today I updated the generated EXI code in the libiso15118 library. With the latest cbexigen main commit and xmlschema 2.5.0. And the d20 communication works as it should.

Then I create a branch here and test with xmlschema 2.5.0 :+1:

**Comment by zhenbin-lin** [comment]
hi:
   i excute  python src/main.py then issue a error as follow:

Traceback (most recent call last):
  File "G:\cbexigen-main\src\main.py", line 11, in <module>
    from cbexigen import FileGenerator as Generator
  File "G:\cbexigen-main\src\cbexigen\FileGenerator.py", line 7, in <module>
    from cbexigen import SchemaAnalyzer as Analyzer
  File "G:\cbexigen-main\src\cbexigen\SchemaAnalyzer.py", line 7, in <module>
    from xmlschema import XMLSchema11, XsdElement, XsdType, XsdAttribute
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\__init__.py", line 20, in <module>
    from .dataobjects import DataElement, DataElementConverter, DataBindingConverter
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\dataobjects.py", line 22, in <module>
    from . import validators
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\__init__.py", line 38, in <module>
    from .schemas import XMLSchemaMeta, XMLSchemaBase, XMLSchema, XMLSchema10, XMLSchema11
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 2154, in <module>
    class XMLSchema10(XMLSchemaBase):
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 150, in __new__
    meta_schema = meta_schema_class.create_meta_schema(meta_schema_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 772, in create_meta_schema
    meta_schema = meta_schema_class(source, XSD_NAMESPACE, global_maps=global_maps,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 361, in __init__
    self.source = XMLResource(source, base_url, allow, defuse, timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 513, in __init__
    self.parse(source, lazy)
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 748, in parse
    url = normalize_url(source, self._base_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 188, in normalize_url
    path = _PurePath.from_uri(url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 115, in from_uri
    return _PureWindowsPath(uri)  # Eg. k:/Python/lib/....
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 98, in __new__
    return cast('_PurePath', cls._from_parts(args))
                             ^^^^^^^^^^^^^^^
AttributeError: type object '_PureWindowsPath' has no attribute '_from_parts'. Did you mean: '_load_parts'?

i don't undestand python. this problem is some with this issue ?

**Comment by zhenbin-lin** [comment]
my python version is python3.12

**Comment by zhenbin-lin** [comment]
> hi: i excute python src/main.py then issue a error as follow:
> 
> Traceback (most recent call last): File "G:\cbexigen-main\src\main.py", line 11, in from cbexigen import FileGenerator as Generator File "G:\cbexigen-main\src\cbexigen\FileGenerator.py", line 7, in from cbexigen import SchemaAnalyzer as Analyzer File "G:\cbexigen-main\src\cbexigen\SchemaAnalyzer.py", line 7, in from xmlschema import XMLSchema11, XsdElement, XsdType, XsdAttribute File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema__init__.py", line 20, in from .dataobjects import DataElement, DataElementConverter, DataBindingConverter File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\dataobjects.py", line 22, in from . import validators File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators__init__.py", line 38, in from .schemas import XMLSchemaMeta, XMLSchemaBase, XMLSchema, XMLSchema10, XMLSchema11 File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 2154, in class XMLSchema10(XMLSchemaBase): File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 150, in **new** meta_schema = meta_schema_class.create_meta_schema(meta_schema_file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 772, in create_meta_schema meta_schema = meta_schema_class(source, XSD_NAMESPACE, global_maps=global_maps, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\validators\schemas.py", line 361, in **init** self.source = XMLResource(source, base_url, allow, defuse, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 513, in **init** self.parse(source, lazy) File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 748, in parse url = normalize_url(source, self._base_url) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 188, in normalize_url path = _PurePath.from_uri(url) ^^^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 115, in from_uri return _PureWindowsPath(uri) # Eg. k:/Python/lib/.... ^^^^^^^^^^^^^^^^^^^^^ File "E:\Users\BinWatson\AppData\Local\Programs\Python\Python312\Lib\site-packages\xmlschema\resources.py", line 98, in **new** return cast('_PurePath', cls._from_parts(args)) ^^^^^^^^^^^^^^^ AttributeError: type object '_PureWindowsPath' has no attribute '_from_parts'. Did you mean: '_load_parts'?
> 
> i don't undestand python. this problem is some with this issue ?

I have fix this problem by update my xmlschema!!!

**Comment by SebaLukas** [comment]
Yes, this is the same error message I had.
Another possibility would be to use an "older" Python version 3.11 or lower.

**Comment by barsnick** [comment]
xmlschema 3.0.0 is released:
[Release notes xmlschema 3.0.0](https://github.com/sissaschool/xmlschema/releases/tag/v3.0.0)
